# -*- coding: utf-8 -*-
"""11-11-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahNk91dYu4GB9n7lCYORL9CoIpVE3FzV
"""

from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()


import matplotlib.pyplot as plt
import numpy as np

np.random.seed(43)

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'sheep', 'truck']

sample_size = 9
random_six = np.random.randint(50000, size=sample_size)

plt.figure(figsize = (5,5))
for i, idx in enumerate(random_six):
  plt.subplot(3,3,i+1)
  plt.xticks([])
  plt.yticks([])
  plt.imshow(x_train[i], cmap='gray')
  plt.xlabel(class_names[int(y_train[i])])
plt.show()

x_mean = np.mean(x_train, axis=(0,1,2))
x_std = np.std(x_train, axis = (0,1,2))
x_mean, x_std

print(x_train.shape)
print(x_train)

x_train = (x_train - x_mean) / x_std
x_test = (x_test - x_mean) / x_std
x_train, x_test

